name: DBT-CORE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dbt_run:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Forzar instalación limpia de Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          architecture: 'x64'
          
      - name: Verificar versión de Python
        run: python --version

      - name: Instalar ODBC Driver para SQL Server (Windows)
        shell: powershell
        run: |
          $url = "https://aka.ms/download-odbc-driver-18-windows-x64"
          $output = "$env:TEMP\msodbcsql.msi"
          Invoke-WebRequest -Uri $url -OutFile $output
          Start-Process msiexec.exe -ArgumentList "/i $output /quiet /norestart IACCEPTMSODBCSQLLICENSETERMS=YES" -Wait

      - name: Instalar DBT para SQL Server
        run: pip install dbt-core==1.8.9 dbt-sqlserver==1.8.7

      - name: Crear directorio .dbt (PowerShell)
        shell: powershell
        run: |
          if (-Not (Test-Path -Path $HOME\.dbt)) {
            New-Item -ItemType Directory -Path $HOME\.dbt
          }

      - name: Cargar profiles.yml desde secretos (PowerShell)
        shell: powershell
        run: |
          $content = '${{ secrets.DBT_PROFILES_YML }}'
          $content | Out-File -FilePath $HOME\.dbt\profiles.yml -Encoding utf8

      - name: Compilar modelos (PowerShell)
        shell: powershell
        run: |
          dbt deps
          dbt compile

      - name: Ejecutar tests (raw y staging)
        run: dbt test --select raw staging --store-failures

      - name: Ejecutar modelos RAW
        run: dbt run --select raw --threads 1

      - name: Ejecutar modelos STAGING
        run: dbt run --select staging --threads 1

      - name: Generar documentación
        run: dbt docs generate

      - name: Guardar manifest.json como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: target/manifest.json
