name: DBT-CORE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dbt_run:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Forzar instalación limpia de Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          architecture: 'x64'
          
      - name: Verificar versión de Python
        run: python --version

      - name: Instalar ODBC Driver para SQL Server
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y curl gnupg2 unixodbc-dev
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17

      - name: Instalar DBT para SQL Server
        run: pip install dbt-core==1.8.9 dbt-sqlserver==1.8.7

      - name: Crear directorio .dbt
        run: mkdir -p ~/.dbt

      - name: Cargar profiles.yml desde secretos
        run: echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: Compilar modelos
        run: dbt deps && dbt compile

      - name: Ejecutar tests (raw y staging)
        run: dbt test --select raw staging --store-failures

      - name: Ejecutar modelos RAW
        run: dbt run --select raw --threads 2

      - name: Ejecutar modelos STAGING
        run: dbt run --select staging --threads 2

      - name: Generar documentación
        run: dbt docs generate

      - name: Guardar manifest.json como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: target/manifest.json
